version: 1
formatters:
  default:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: '%Y-%m-%d %H:%M:%S'
  train:
    format: "Training: %(asctime)s-%(message)s"
handlers:
  console:
    formatter: default
    class: logging.StreamHandler
    level: INFO
    stream: ext://sys.stdout
  train:
    class: logging.FileHandler
    formatter: train
    level: INFO
    filename: logs/training.log
  error:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: default
    filename: logs/error.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8
loggers:
  train:
    level: DEBUG
    handlers: [train, error]
root:
  level: INFO
  handlers: [console]