version: 1
formatters:
  default:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: '%Y-%m-%d %H:%M:%S'
  train:
    format: "Training: %(asctime)s-%(message)s"
handlers:
  console:
    formatter: default
    class: logging.StreamHandler
    level: INFO
    stream: ext://sys.stdout
  train:
    class: logging.FileHandler
    formatter: train
    level: INFO
    filename: logs/training.log
  train_cross:
    class: logging.FileHandler
    formatter: train
    level: INFO
    filename: logs/train_cross2.log
  train_cosface:
    class: logging.FileHandler
    formatter: train
    level: INFO
    filename: logs/train_cosface.log
  train_arcface:
    class: logging.FileHandler
    formatter: train
    level: INFO
    filename: logs/train_arcface.log
  error:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: default
    filename: logs/error.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8
loggers:
  train:
    level: DEBUG
    handlers: [train, error]
  train_cross:
    level: DEBUG
    handlers: [train_cross]
  train_cosface:
    level: DEBUG
    handlers: [train_cosface]
  train_arcface:
    level: DEBUG
    handlers: [train_arcface]
root:
  level: INFO
  handlers: [console]